"""empty message

Revision ID: 1391d41ae52b
Revises: 13dd3914e8d9
Create Date: 2022-05-17 20:08:22.678425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1391d41ae52b'
down_revision = '13dd3914e8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nacimiento', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('nombre', sa.String(length=80), nullable=True))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'nombre')
    op.drop_column('user', 'nacimiento')
    # ### end Alembic commands ###
